//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Sample_3.ORM
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ReservationContainer : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ReservationContainer”部分中的连接字符串初始化新 ReservationContainer 对象。
        /// </summary>
        public ReservationContainer() : base("name=ReservationContainer", "ReservationContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ReservationContainer 对象。
        /// </summary>
        public ReservationContainer(string connectionString) : base(connectionString, "ReservationContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ReservationContainer 对象。
        /// </summary>
        public ReservationContainer(EntityConnection connection) : base(connection, "ReservationContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ReservationContent> ReservationContent
        {
            get
            {
                if ((_ReservationContent == null))
                {
                    _ReservationContent = base.CreateObjectSet<ReservationContent>("ReservationContent");
                }
                return _ReservationContent;
            }
        }
        private ObjectSet<ReservationContent> _ReservationContent;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserReservationContent> UserReservationContent
        {
            get
            {
                if ((_UserReservationContent == null))
                {
                    _UserReservationContent = base.CreateObjectSet<UserReservationContent>("UserReservationContent");
                }
                return _UserReservationContent;
            }
        }
        private ObjectSet<UserReservationContent> _UserReservationContent;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserReservation> UserReservation
        {
            get
            {
                if ((_UserReservation == null))
                {
                    _UserReservation = base.CreateObjectSet<UserReservation>("UserReservation");
                }
                return _UserReservation;
            }
        }
        private ObjectSet<UserReservation> _UserReservation;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Reservation> Reservation
        {
            get
            {
                if ((_Reservation == null))
                {
                    _Reservation = base.CreateObjectSet<Reservation>("Reservation");
                }
                return _Reservation;
            }
        }
        private ObjectSet<Reservation> _Reservation;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 ReservationContent EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToReservationContent(ReservationContent reservationContent)
        {
            base.AddObject("ReservationContent", reservationContent);
        }
    
        /// <summary>
        /// 用于向 UserReservationContent EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserReservationContent(UserReservationContent userReservationContent)
        {
            base.AddObject("UserReservationContent", userReservationContent);
        }
    
        /// <summary>
        /// 用于向 UserReservation EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserReservation(UserReservation userReservation)
        {
            base.AddObject("UserReservation", userReservation);
        }
    
        /// <summary>
        /// 用于向 Reservation EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToReservation(Reservation reservation)
        {
            base.AddObject("Reservation", reservation);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Reservation", Name="Reservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reservation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Reservation 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        public static Reservation CreateReservation(global::System.Int32 id, global::System.String name)
        {
            Reservation reservation = new Reservation();
            reservation.ID = id;
            reservation.Name = name;
            return reservation;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Reservation", Name="ReservationContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReservationContent : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ReservationContent 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="content">Content 属性的初始值。</param>
        /// <param name="reservationID">ReservationID 属性的初始值。</param>
        public static ReservationContent CreateReservationContent(global::System.Int32 id, global::System.String name, global::System.String content, global::System.Int32 reservationID)
        {
            ReservationContent reservationContent = new ReservationContent();
            reservationContent.ID = id;
            reservationContent.Name = name;
            reservationContent.Content = content;
            reservationContent.ReservationID = reservationID;
            return reservationContent;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false, "Content");
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReservationID
        {
            get
            {
                return _ReservationID;
            }
            set
            {
                OnReservationIDChanging(value);
                ReportPropertyChanging("ReservationID");
                _ReservationID = StructuralObject.SetValidValue(value, "ReservationID");
                ReportPropertyChanged("ReservationID");
                OnReservationIDChanged();
            }
        }
        private global::System.Int32 _ReservationID;
        partial void OnReservationIDChanging(global::System.Int32 value);
        partial void OnReservationIDChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Reservation", Name="UserReservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserReservation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserReservation 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="weixinOpenId">WeixinOpenId 属性的初始值。</param>
        /// <param name="reservationID">ReservationID 属性的初始值。</param>
        public static UserReservation CreateUserReservation(global::System.Int32 id, global::System.String weixinOpenId, global::System.Int32 reservationID)
        {
            UserReservation userReservation = new UserReservation();
            userReservation.ID = id;
            userReservation.WeixinOpenId = weixinOpenId;
            userReservation.ReservationID = reservationID;
            return userReservation;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WeixinOpenId
        {
            get
            {
                return _WeixinOpenId;
            }
            set
            {
                OnWeixinOpenIdChanging(value);
                ReportPropertyChanging("WeixinOpenId");
                _WeixinOpenId = StructuralObject.SetValidValue(value, false, "WeixinOpenId");
                ReportPropertyChanged("WeixinOpenId");
                OnWeixinOpenIdChanged();
            }
        }
        private global::System.String _WeixinOpenId;
        partial void OnWeixinOpenIdChanging(global::System.String value);
        partial void OnWeixinOpenIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReservationID
        {
            get
            {
                return _ReservationID;
            }
            set
            {
                OnReservationIDChanging(value);
                ReportPropertyChanging("ReservationID");
                _ReservationID = StructuralObject.SetValidValue(value, "ReservationID");
                ReportPropertyChanged("ReservationID");
                OnReservationIDChanged();
            }
        }
        private global::System.Int32 _ReservationID;
        partial void OnReservationIDChanging(global::System.Int32 value);
        partial void OnReservationIDChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Reservation", Name="UserReservationContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserReservationContent : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserReservationContent 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="content">Content 属性的初始值。</param>
        /// <param name="userReservationId">UserReservationId 属性的初始值。</param>
        /// <param name="reservationContentId">ReservationContentId 属性的初始值。</param>
        public static UserReservationContent CreateUserReservationContent(global::System.Int32 id, global::System.String content, global::System.Int32 userReservationId, global::System.Int32 reservationContentId)
        {
            UserReservationContent userReservationContent = new UserReservationContent();
            userReservationContent.ID = id;
            userReservationContent.Content = content;
            userReservationContent.UserReservationId = userReservationId;
            userReservationContent.ReservationContentId = reservationContentId;
            return userReservationContent;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false, "Content");
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserReservationId
        {
            get
            {
                return _UserReservationId;
            }
            set
            {
                OnUserReservationIdChanging(value);
                ReportPropertyChanging("UserReservationId");
                _UserReservationId = StructuralObject.SetValidValue(value, "UserReservationId");
                ReportPropertyChanged("UserReservationId");
                OnUserReservationIdChanged();
            }
        }
        private global::System.Int32 _UserReservationId;
        partial void OnUserReservationIdChanging(global::System.Int32 value);
        partial void OnUserReservationIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReservationContentId
        {
            get
            {
                return _ReservationContentId;
            }
            set
            {
                OnReservationContentIdChanging(value);
                ReportPropertyChanging("ReservationContentId");
                _ReservationContentId = StructuralObject.SetValidValue(value, "ReservationContentId");
                ReportPropertyChanged("ReservationContentId");
                OnReservationContentIdChanged();
            }
        }
        private global::System.Int32 _ReservationContentId;
        partial void OnReservationContentIdChanging(global::System.Int32 value);
        partial void OnReservationContentIdChanged();

        #endregion

    }

    #endregion

}
